name: good_trip
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.6.0
  google_fonts: ^6.1.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  equatable: ^2.0.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  iconsax_flutter: ^1.0.0
  get: ^4.6.6
  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  json_annotation: ^4.9.0
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  auto_route: ^8.3.0
  auto_route_generator: ^8.0.0
  animated_splash_screen: ^1.3.0
  day_picker: 2.2.0
  image_picker: ^1.0.8
  get_it: ^7.6.7
  injectable: ^2.3.5
  freezed_annotation: ^2.4.1
  file_picker: ^8.0.0+1
  just_audio: ^0.9.37
  multiselect: ^0.1.0
  dio_interceptor_plus: ^0.0.2
  retrofit: ^4.2.0
  smooth_page_indicator: ^1.2.0+3
  flutter_native_splash: ^2.4.1
  dropdown_button2: ^2.3.9
  firebase_core: ^3.4.0
  firebase_analytics: ^11.3.0
  firebase_app_check: ^0.3.1
  firebase_messaging: ^15.1.0
  firebase_in_app_messaging: ^0.8.0+5
  onesignal_flutter: ^5.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  injectable_generator:
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  retrofit_generator: '>=7.0.0 <8.0.0'
  analyzer: ^6.7.0

flutter_native_splash:
#  color: "FF9EA2"
#  image: assets/images/splash.png
  background_image_android: assets/images/splash.png
  background_image_ios: assets/images/splash.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/temperature_512.png
    - assets/images/logo.png
    - assets/images/logo_with_name.png
    - assets/images/splash.png
    - assets/fonts/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gilroy-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Gilroy-Light.otf
          weight: 300
