version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'localguide'
      POSTGRES_PASSWORD: '1234'

  adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8080"
